name: Lint test

on:
  pull_request:

jobs:

  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
      - name: ğŸš€ Run hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-check
          filter_mode: nofilter

  remark-lint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2
      - name: ğŸš€ Run remark-lint
        uses: reviewdog/action-remark-lint@v5
        with:
          reporter: github-pr-check
          filter_mode: nofilter
